import type { Post } from '@/types'

const now = Date.now()
const ago = (ms: number) => new Date(now - ms).toISOString()

export const MOCK_POSTS: Post[] = [
  {
    id: 'mock-1',
    user_id: 'u1',
    user: { id: 'u1', username: 'özgür leş', email: '', avatar_url: '', bio: '', role: 'admin', created_at: ago(86400000) },
    category_id: 1,
    category: { id: 1, name: 'hiperfokus', slug: 'hiperfokus', icon: '👁', description: '', order: 1 },
    title: 'Dikkat dağıtıcıları azaltmanın 5 pratik yolu',
    body: 'Modern dünyada dikkatimizi çeken her şeyi değil, sadece önemli olanı seçmek giderek zorlaşıyor. Beynimizin odaklanma mekanizmasını ve onu nasıl geliştirebileceğimizi bu yazıda inceliyoruz. Derin çalışma (deep work) kavramından başlayarak günlük rutinlerimizi nasıl yeniden şekillendirebileceğimizi konuşacağız.',
    post_type: 'article',
    metadata: {},
    like_count: 127,
    comment_count: 23,
    created_at: ago(7200000),
    updated_at: ago(7200000),
  },
  {
    id: 'mock-2',
    user_id: 'u2',
    user: { id: 'u2', username: 'buğra atmaca', email: '', avatar_url: '', bio: '', role: 'user', created_at: ago(86400000) },
    category_id: 2,
    category: { id: 2, name: 'dipses', slug: 'dipses', icon: '🎧', description: '', order: 2 },
    title: 'Zeki Demirkubuz — Kış Uykusu Üzerine',
    body: '',
    post_type: 'embed',
    metadata: {
      url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
      embed_url: 'https://www.youtube.com/embed/oHg5SJYRHA0',
      video_id: 'oHg5SJYRHA0',
    },
    like_count: 89,
    comment_count: 15,
    created_at: ago(300000),
    updated_at: ago(300000),
  },
  {
    id: 'mock-3',
    user_id: 'u3',
    user: { id: 'u3', username: 'dilhan şeşen', email: '', avatar_url: '', bio: '', role: 'user', created_at: ago(86400000) },
    category_id: 6,
    category: { id: 6, name: 'hemfikir', slug: 'hemfikir', icon: '🙌', description: '', order: 6 },
    title: 'En iyi dönem film müziği bestecisi?',
    body: '',
    post_type: 'poll',
    metadata: {
      options: [
        { id: 'o1', text: 'Ennio Morricone', votes: 142 },
        { id: 'o2', text: 'Hans Zimmer', votes: 98 },
        { id: 'o3', text: 'John Williams', votes: 215 },
        { id: 'o4', text: 'Bernard Herrmann', votes: 64 },
      ],
      total_votes: 519,
    },
    like_count: 34,
    comment_count: 47,
    created_at: ago(1800000),
    updated_at: ago(1800000),
  },
  {
    id: 'mock-4',
    user_id: 'u4',
    user: { id: 'u4', username: 'sine sayko', email: '', avatar_url: '', bio: '', role: 'user', created_at: ago(86400000) },
    category_id: 5,
    category: { id: 5, name: 'sualite', slug: 'sualite', icon: '⚡', description: '', order: 5 },
    title: 'Yapay zekanın müzik endüstrisine etkisi üzerine',
    body: '',
    post_type: 'link',
    metadata: {
      url: 'https://pitchfork.com',
      link_title: 'How AI Is Changing the Music Industry Forever',
      link_description: 'A deep dive into how artificial intelligence is reshaping everything from music creation to distribution and the economics of the entire industry.',
      link_domain: 'pitchfork.com',
      link_image: '',
    },
    like_count: 56,
    comment_count: 12,
    created_at: ago(10800000),
    updated_at: ago(10800000),
  },
  {
    id: 'mock-5',
    user_id: 'u5',
    user: { id: 'u5', username: 'ilker kocael', email: '', avatar_url: '', bio: '', role: 'user', created_at: ago(86400000) },
    category_id: 3,
    category: { id: 3, name: 'sinemaskop', slug: 'sinemaskop', icon: '🎬', description: '', order: 3 },
    title: 'Nuri Bilge Ceylan sinemasında sessizliğin dili',
    body: 'Sessizlik, Ceylan filmlerinde konuşmayı aşan bir anlatı aracına dönüşür. Karakterlerin söylemediği şeyler, söylediklerinden çok daha yüklüdür. Bu yazıda Uzak\'tan Kış Uykusu\'na uzanan bir hat çizerek bu sessizliklerin ne anlattığını keşfediyoruz.',
    post_type: 'article',
    metadata: {},
    like_count: 203,
    comment_count: 31,
    created_at: ago(18000000),
    updated_at: ago(18000000),
  },
]
